packages:
  - 'apps/*'

overrides:
  esbuild: "^0.25.0"

allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  '@scarf/scarf': true
  'esbuild': true
  'prisma': true
  'unrs-resolver': true
